services:
  app:
    build: .
    container_name: carbonquest-api
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "4000:4000" # HOST:CONTAINER, sekarang pakai 4000
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules

  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: carbonquest-tunnel
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=eyJhIjoiMWE0YTM1MGQ3M2EyYTQ5ZmNjNjdhMmE0NDc4Zjk1NDAiLCJ0IjoiNTQ3NmE4OTYtOGM2Ni00NWFjLTk5NGItNDlmZTE3NmZhMjZjIiwicyI6Ik1qWTNNRGxpTldJdE9XVmxNUzAwWXpJeUxUazJNell0TkRoaE4ySXlOakJoTW1NNSJ9
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    container_name: carbonquest-db
    environment:
      POSTGRES_USER: carbonquest
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: carbonquest_db
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  db_data:
